apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-definite-walleye
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "382049671757"
    kanikoFlags: --skip-unused-stages --snapshotMode=redo
    project: micro-183808
    provider: gke
    registry: gcr.io
    zone: asia-east1-b
  environments:
  - key: dev
    owner: genekuo-org
    repository: jx3-demo-walk-cluster
  - key: staging
  - key: production
  ingress:
    domain: 35.229.148.236.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  kuberhealthy: true
  pipelineUser:
    username: genekuo-org
  repository: nexus
  secretStorage: gsm
  storage:
  - name: logs
    url: gs://logs-tf-jx-definite-walleye-6dc923358af8
  - name: reports
    url: gs://reports-tf-jx-definite-walleye-6dc923358af8
  - name: repository
    url: gs://repository-tf-jx-definite-walleye-6dc923358af8
  vault: {}
  webhook: lighthouse
